### PR TITLE
Fixed indexing on the maximum decomposition rate

### PR DESCRIPTION
**Pull request by rgknox**
fixes indexing on accessing the max decomposition parameter array

### CODE REVIEW

**Comment by huangmy** [comment]
@rgknox Have you tested the change? If yes, I will merge it.

**Comment by rgknox** [comment]
yes, I have tested this on cheyenne, all tests pass now, and bit-for-bit with baseline too

**Comment by huangmy** [comment]
Sounds great. Merging now.

**Comment by huangmy** [comment]
@rgknox : I have merged it into my branch.

**Pull request merged**
